### Installation Libraries
You have to Import the required dependencies 
- cv2 - To read the image and resize the image
- scipy - To savae the image array to .mat file 
- numpy to store multi-dimensional array 

#### Step 1
Store the path of the class in the dictionary 


In [25]:
import os
import cv2
import numpy as np
from scipy.io import savemat

dataset = {}  # Dictionary to hold the dataset

# Define the paths to the class folders
class_folders = {
    'traffic_incident': 'C:/Users/Pc/Downloads/Compressed/AIDER/AIDER/traffic_incident',
    'collapsed_building': 'C:/Users/Pc/Downloads/Compressed/AIDER/AIDER/collapsed_building',
    'fire': 'C:/Users/Pc/Downloads/Compressed/AIDER/AIDER/fire',
    'flooded_areas': 'C:/Users/Pc/Downloads/Compressed/AIDER/AIDER/flooded_areas',
    'normal': 'C:/Users/Pc/Downloads/Compressed/AIDER/AIDER/normal'
}



#### Step 3
 - For each Class label and Label Dictionary store each path of image
 - Read the image and resize each image to 64 by 64
 - Store the image data to list correspondance to the current class name
 - Store all the classes in the **Dataset** 
 - Store this **Dataset** file in .mat file using savemat function of scipy
  

In [27]:
import numpy as np
from scipy.io import savemat

dataset = {}  # Dictionary to store the dataset

for class_label, folder_path in class_folders.items():
    print("On Label: ", class_label)
    class_data = []  # List to store image data for the current class

    # Iterate through the images in the class folder
    for filename in os.listdir(folder_path):
        image_path = os.path.join(folder_path, filename)

        # Load the image using OpenCV or PIL
        image = cv2.imread(image_path)  # Example using OpenCV
        image = cv2.resize(image , (64 , 64))
        
        # Append the image data to the class_data list
        class_data.append(image)

    # Convert the class_data list to a numpy array
    class_data = np.array(class_data)

    # Store the class_data array in the dataset dictionary
    dataset[class_label] = class_data

# Save the dataset as a MAT file
savemat('AIDER_resize_64by64_dataset.mat', dataset)


On Label:  traffic_incident
On Label:  collapsed_building
On Label:  fire
On Label:  flooded_areas
On Label:  normal


#### Cross-Check
- Read the mat file to check all the label with correct name is present 

In [1]:
from scipy.io import loadmat

# Load the MAT file
data = loadmat('AIDER2_dataset.mat')

# View the variables in the MAT file
print(data.keys())

# Access a specific variable
variable_name = 'traffic_incident'  # Replace with the desired variable name
variable_data = data[variable_name]
print(variable_data)


dict_keys(['__header__', '__version__', '__globals__', 'traffic_incident', 'collapsed_building', 'fire', 'flooded_areas', 'normal'])
[[[[ 32  22  35]
   [ 57  47  59]
   [ 85  74  85]
   ...
   [125 149 149]
   [139 163 163]
   [141 165 165]]

  [[119 108 121]
   [133 123 135]
   [152 140 152]
   ...
   [139 163 163]
   [145 169 169]
   [138 162 162]]

  [[164 154 167]
   [168 158 170]
   [187 175 187]
   ...
   [150 174 174]
   [132 156 156]
   [116 140 140]]

  ...

  [[ 40  49  39]
   [ 46  57  47]
   [ 48  57  47]
   ...
   [ 89 137 125]
   [ 87 137 125]
   [ 88 137 125]]

  [[ 40  47  38]
   [ 44  53  43]
   [ 34  42  32]
   ...
   [ 84 134 122]
   [ 78 128 116]
   [ 75 126 113]]

  [[ 36  40  34]
   [ 51  58  51]
   [ 50  54  48]
   ...
   [ 89 142 129]
   [ 75 128 115]
   [ 82 135 122]]]


 [[[116 127 135]
   [100 111 118]
   [104 114 121]
   ...
   [173 176 189]
   [173 176 189]
   [173 176 190]]

  [[115 126 134]
   [ 82  93 101]
   [106 116 124]
   ...
   [173 177 187]
   [17